import { FileNode } from './types';

const PLACEHOLDER_PYTHON = `# Placeholder content
# This file was generated by Flexcyz Architect

def main():
    pass

if __name__ == "__main__":
    main()
`;

const DOCKER_COMPOSE = `version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
`;

const MAIN_PY = `# FastAPI entry + WebSocket
from fastapi import FastAPI, WebSocket
from flexcyz.core.orchestrator import Orchestrator

app = FastAPI(title="Flexcyz API")
orchestrator = Orchestrator()

@app.get("/")
async def root():
    return {"status": "online", "system": "Flexcyz v1.0"}

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    # TODO: Implement real-time agent communication
    while True:
        data = await websocket.receive_text()
        await websocket.send_text(f"Message received: {data}")
`;

const CONFIG_PY = `# Settings & env vars
import os
from pydantic import BaseSettings

class Settings(BaseSettings):
    PROJECT_NAME: str = "Flexcyz"
    REDIS_URL: str = os.getenv("REDIS_URL", "redis://localhost:6379/0")
    OPENAI_API_KEY: str = os.getenv("OPENAI_API_KEY", "")
    
    class Config:
        env_file = ".env"

settings = Settings()
`;

const SYSTEM_PROMPTS = `# Agent behavior definitions
agents:
  planner:
    role: "Senior Project Manager"
    goal: "Break down complex user requests into actionable tasks."
  architect:
    role: "Systems Architect"
    goal: "Design scalable file structures and component relationships."
  coder:
    role: "Senior Python Developer"
    goal: "Write clean, efficient, and typed Python code."
`;

// Helper to create a file node
const file = (name: string, content: string = PLACEHOLDER_PYTHON, language: string = 'python'): FileNode => ({
  id: crypto.randomUUID(),
  name,
  type: 'file',
  content,
  language
});

// Helper to create a folder node
const folder = (name: string, children: FileNode[] = []): FileNode => ({
  id: crypto.randomUUID(),
  name,
  type: 'folder',
  children,
  isOpen: false
});

export const INITIAL_FILE_TREE: FileNode[] = [
  folder('flexcyz', [
    file('docker-compose.yml', DOCKER_COMPOSE, 'yaml'),
    folder('backend', [
      file('__init__.py', '', 'python'),
      file('main.py', MAIN_PY, 'python'),
      file('config.py', CONFIG_PY, 'python'),
      folder('core', [
        file('__init__.py', '', 'python'),
        file('orchestrator.py', '# Task router & queue\n\nclass Orchestrator:\n    def __init__(self):\n        pass\n\n    def route_task(self, task):\n        pass', 'python'),
        file('memory.py', '# Redis/JSON persistence\n\nclass MemoryManager:\n    def __init__(self):\n        pass', 'python'),
        file('state_manager.py', '# Project state machine\n\nclass StateManager:\n    def __init__(self):\n        pass', 'python'),
      ]),
      folder('agents', [
        file('__init__.py', '', 'python'),
        file('base.py', '# Base agent class\n\nclass BaseAgent:\n    def __init__(self, role, goal):\n        self.role = role\n        self.goal = goal\n\n    def execute(self, task):\n        raise NotImplementedError', 'python'),
        file('planner.py', '# Expands prompts to tasks\nfrom .base import BaseAgent\n\nclass Planner(BaseAgent):\n    pass', 'python'),
        file('architect.py', '# Designs system structure\nfrom .base import BaseAgent\n\nclass Architect(BaseAgent):\n    pass', 'python'),
        file('coder.py', '# Generates code files\nfrom .base import BaseAgent\n\nclass Coder(BaseAgent):\n    pass', 'python'),
        file('reviewer.py', '# Code review & fixes\nfrom .base import BaseAgent\n\nclass Reviewer(BaseAgent):\n    pass', 'python'),
        file('researcher.py', '# Web search & docs\nfrom .base import BaseAgent\n\nclass Researcher(BaseAgent):\n    pass', 'python'),
        file('github_agent.py', '# Git operations\nfrom .base import BaseAgent\n\nclass GithubAgent(BaseAgent):\n    pass', 'python'),
        file('deployer.py', '# Vercel/Railway deploy\nfrom .base import BaseAgent\n\nclass Deployer(BaseAgent):\n    pass', 'python'),
      ]),
      folder('tools', [
        file('__init__.py', '', 'python'),
        file('llm_router.py', '# Multi-model abstraction\n\nclass LLMRouter:\n    def route(self, prompt):\n        pass', 'python'),
        file('sandbox.py', '# Docker code execution\n\nclass Sandbox:\n    def run(self, code):\n        pass', 'python'),
        file('web_search.py', '# Tavily/Exa integration\n\nclass WebSearch:\n    def search(self, query):\n        pass', 'python'),
        file('file_manager.py', '# CRUD operations\n\nclass FileManager:\n    def read(self, path):\n        pass\n\n    def write(self, path, content):\n        pass', 'python'),
        file('git_manager.py', '# Git CLI wrapper\n\nclass GitManager:\n    def clone(self, repo):\n        pass', 'python'),
      ]),
      folder('models', [
        file('__init__.py', '', 'python'),
        file('schemas.py', '# Pydantic models\nfrom pydantic import BaseModel\n\nclass ProjectSchema(BaseModel):\n    name: str', 'python'),
      ]),
    ]),
    folder('frontend', [
      file('index.html', '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>Flexcyz App</title>\n</head>\n<body>\n    <div id="app"></div>\n</body>\n</html>', 'html'),
      folder('css', [
        file('orchid-theme.css', '/* Dark IDE styling */\nbody {\n    background-color: #1e1e2e;\n    color: #cdd6f4;\n}', 'css'),
      ]),
      folder('js', [
        file('app.js', '// Main app logic\ndocument.addEventListener("DOMContentLoaded", () => {\n    console.log("App initialized");\n});', 'javascript'),
        file('editor.js', '// CodeMirror 6 setup\nexport function setupEditor(element) {\n    // Initialize editor\n}', 'javascript'),
        file('websocket.js', '// Real-time sync\nconst socket = new WebSocket("ws://localhost:8000/ws");\n\nsocket.onmessage = (event) => {\n    console.log(event.data);\n};', 'javascript'),
        file('orchid-ui.js', '// Custom UI components\nclass OrchidComponent extends HTMLElement {\n    connectedCallback() {\n        this.innerHTML = "<div>Orchid UI</div>";\n    }\n}\ncustomElements.define("orchid-component", OrchidComponent);', 'javascript'),
      ]),
    ]),
    folder('prompts', [
      file('system_prompts.yaml', SYSTEM_PROMPTS, 'yaml'),
      folder('templates', [
         file('fastapi_crud.py', '# Code generation template for FastAPI CRUD', 'python'),
         file('react_component.tsx', '// Code generation template for React Component', 'typescript'),
      ])
    ])
  ])
];